version: '3'

services:
  chinchilla:
    build:
      context: ./Chinchilla
      dockerfile: Dockerfile

    ports:
      - 3000:3000
    volumes:
      - ./Chinchilla/node_modules:/app/node_modules

