version: "3"

services:
  redis:
    build: "./redis"
    container_name: redis
    networks:
      - default
    ports: 6379:6379
    volumes:
      - "./volumes/redis/data:/data"
    networks:
      ipv4_address: 172.21.0.101

  web2:
    image: nginx:alpine

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24