apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: docker.io/library/rei-api
      context: ../../rei-api
      docker:
        dockerfile: ../rei-api/Dockerfile
        noCache: false
        squash: false
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    dateTime:
      format: "20060102_150405"
      timezone: "Local"
deploy:
  helm:
    releases:
      - name: rei-api
        namespace: rei
        createNamespace: true
        chartPath: ../rei-api/
        valuesFiles:
          - "../rei-api/values.dev.yaml"
        setValues:
          image:
            imagePullPolicy: Always
        artifactOverrides:
          image: docker.io/library/rei-api
        imageStrategy:
          helm: {}
portForward:
- resourceType: Service
  resourceName: rei-api-service
  namespace: rei
  port: 8000
  address: 0.0.0.0
  localPort: 8000