version: "3"

services:
  chinchilla:
    build:
      context: ./chinchilla
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./chinchilla:/app/
      - /app/node_modules
      - /app/.next

  baboon:
    build:
      context: ./baboon
      dockerfile: Dockerfile
    volumes:
      - ./baboon:/app/
      - /app/node_modules

  nginx:
    build:
      context: ./environments/images/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./baboon/public:/var/www/html
