version: "3"

services:
  chinchilla:
    build:
      context: ./chinchilla
      dockerfile: Dockerfile

    ports:
      - 3000:3000
    volumes:
      - ./chinchilla:/app/
      - ./chinchilla/node_modules:/app/node_modules

  baboon:
    build:
      context: ./baboon
      dockerfile: Dockerfile

    ports:
      - 3001:3001
    volumes:
      - ./baboon:/app/
      - ./baboon/node_modules:/app/node_modules
