FROM rust:1.59.0-slim-buster AS chef
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --release


FROM debian:buster-slim
WORKDIR /app
COPY --from=builder /app/target/release/rest rei-api
CMD [ "./rei-api" ]