version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      retries: 10
      timeout: 10s
  api:
    image: python:3
    command: /bin/bash -c "sleep 1 && python -m http.server 8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8888/ || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 10s
    depends_on:
      postgres:
        condition: service_healthy
  healthchecker:
    image: busybox
    depends_on:
      api:
        condition: service_healthy
