version: "3"
services:
  redis:
    image: redis:5.0.6
    container_name: "redis_6333"
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "6333:6379"
    volumes:
      - "./data/redis:/data"
